"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProjectCard } from "./project-card";
import { FluidHero } from "./fluid-hero";
import type { RecipeSummary } from "@/lib/recipe-types";
export function ProjectGallery({ projects, initialQuery = "", initialCategory = "All projects" }: { projects: RecipeSummary[]; initialQuery?: string; initialCategory?: string }) {
  const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState(initialCategory);
  useEffect(() => { const id = window.location.hash.slice(1); if (!id.startsWith("project-")) return; const card = document.getElementById(id); if (card?.matches(".project-card")) card.focus({preventScroll:true}); },[]);
  const ordered = [...projects].sort((a,b) => Number(["supper-club","window-seat"].includes(b.slug)) - Number(["supper-club","window-seat"].includes(a.slug)));
  const filtered = ordered.filter(p => (category === "All projects" || p.category === category) && `${p.title} ${p.summary} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const params = new URLSearchParams(); if (query) params.set("q",query); if (category !== "All projects") params.set("category",category);
  const returnTo = "/" + (params.size ? "?" + params.toString() : "") + "#prompts";
  function filter(value: string) { setCategory(value); const url = new URL(window.location.href); if (value !== "All projects") url.searchParams.set("category",value); else url.searchParams.delete("category"); window.history.replaceState(null,"",url.pathname+url.search+url.hash); }
  function search(value: string) { setQuery(value); const url = new URL(window.location.href); if (value) url.searchParams.set("q", value); else url.searchParams.delete("q"); window.history.replaceState(null, "", url.pathname + url.search + url.hash); }
  return <div className="gallery-page"><section className="atelier-hero"><FluidHero /><h1>Ideas, brought to life.</h1><a className="scroll-badge" href="#prompts" aria-label="Scroll to selected projects"><svg viewBox="0 0 100 100" aria-hidden="true"><defs><path id="scroll-circle" d="M50,50 m-34,0 a34,34 0 1,1 68,0 a34,34 0 1,1 -68,0" /></defs><text><textPath href="#scroll-circle">SCROLL DOWN · SCROLL DOWN · </textPath></text><path d="M50 36v28m-8-8 8 8 8-8" fill="none" stroke="currentColor" /></svg></a></section><section id="prompts" aria-label="Project collection"><div className="collection-intro"><h2><ArrowRight aria-hidden="true" /> Selected projects</h2><p>Try the app. Make it yours.</p></div><div className="gallery-toolbar"><div className="category-filters" aria-label="Filter by project type">{["All projects", "Game", "Web app", "Mini app"].map(c => <Button key={c} variant="ghost" aria-pressed={category === c} onClick={() => filter(c)}>{c}</Button>)}</div><label className="gallery-search"><Search aria-hidden="true" /><span className="sr-only">Search collection</span><Input id="collection-search" aria-label="Search collection" value={query} onChange={event => search(event.target.value)} placeholder="Search the collection" />{query && <Button variant="ghost" size="icon" aria-label="Clear search" onClick={() => search("")}><X /></Button>}</label></div><div className="collection-count" role="status">{filtered.length.toString().padStart(2, "0")} {filtered.length === 1 ? "project" : "projects"}</div>{filtered.length ? <div className={`project-grid ${filtered.length < 3 ? "project-grid-small" : ""}`}>{filtered.map((project, index) => <ProjectCard project={project} position={index} returnTo={returnTo} key={project.id} />)}</div> : <div className="gallery-empty"><h2>{projects.length ? "Nothing here yet." : "New projects are on their way."}</h2><p>{projects.length ? "Try another search or show all projects." : "Check back soon for a new app and its complete recipe."}</p>{projects.length > 0 && <Button variant="outline" onClick={() => { search(""); filter("All projects"); }}>Clear filters</Button>}</div>}</section><footer className="atelier-footer"><Link className="wordmark" href="/">PLS PROMPT</Link><span>Good ideas deserve a head start.</span></footer></div>;
}
