"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProjectCard } from "./project-card";
import { AsciiHero } from "./ascii-hero";
import type { RecipeSummary } from "@/lib/recipe-types";
import type { PromptSummary } from "@/lib/library-types";
export function ProjectGallery({ projects, legacy, initialQuery = "", initialCategory = "All projects" }: { projects: RecipeSummary[]; legacy: PromptSummary[]; initialQuery?: string; initialCategory?: string }) {
  const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState(initialCategory);
  useEffect(() => { const id = window.location.hash.slice(1); if (!id.startsWith("project-")) return; const card = document.getElementById(id); if (card?.matches(".project-card")) card.focus({preventScroll:true}); },[]);
  const filtered = projects.filter(p => (category === "All projects" || p.category === category) && `${p.title} ${p.summary} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const params = new URLSearchParams(); if (query) params.set("q",query); if (category !== "All projects") params.set("category",category);
  const returnTo = "/" + (params.size ? "?" + params.toString() : "") + "#prompts";
  function filter(value: string) { setCategory(value); const url = new URL(window.location.href); if (value !== "All projects") url.searchParams.set("category",value); else url.searchParams.delete("category"); window.history.replaceState(null,"",url.pathname+url.search+url.hash); }
  function search(value: string) { setQuery(value); const url = new URL(window.location.href); if (value) url.searchParams.set("q", value); else url.searchParams.delete("q"); window.history.replaceState(null, "", url.pathname + url.search + url.hash); }
  return <div className="gallery-page"><section className="atelier-hero"><div className="hero-copy"><h1>From prompt<br />to playable.</h1><p>Explore the build. Keep the recipe.</p><a className="hero-index" href="#prompts">01 / THE COLLECTION <ArrowRight aria-hidden="true" /></a></div><div className="hero-art"><AsciiHero /></div></section><section id="prompts" aria-label="Project collection"><div className="gallery-toolbar"><div className="category-filters" aria-label="Filter by project type">{["All projects", "Game", "Web app", "Mini app"].map(c => <Button key={c} variant="ghost" aria-pressed={category === c} onClick={() => filter(c)}>{c}</Button>)}</div><label className="gallery-search"><Search aria-hidden="true" /><span className="sr-only">Search collection</span><Input value={query} onChange={event => search(event.target.value)} placeholder="Find your next build" />{query && <Button variant="ghost" size="icon" aria-label="Clear search" onClick={() => search("")}><X /></Button>}</label></div><div className="collection-count" role="status">{filtered.length.toString().padStart(2, "0")} PROJECTS TO MAKE YOUR OWN</div>{filtered.length ? <div className={`project-grid ${filtered.length < 3 ? "project-grid-small" : ""}`}>{filtered.map((project, index) => <ProjectCard project={project} position={index} returnTo={returnTo} key={project.id} />)}</div> : <div className="gallery-empty"><h2>{projects.length ? "Nothing here yet." : "New projects are on their way."}</h2><p>{projects.length ? "Try another search or show all projects." : "Explore the original prompt collection below."}</p>{projects.length > 0 && <Button variant="outline" onClick={() => { search(""); filter("All projects"); }}>Clear filters</Button>}</div>}</section>{legacy.length > 0 && <section className="legacy-collection"><div><span className="mono-label">THE ORIGINAL COLLECTION</span><h2>More recipes to explore.</h2><p>Our earlier prompts, with their original notes and access.</p></div><div className="legacy-links">{legacy.slice(0,6).map(prompt => <Link href={`/prompts/${prompt.slug}`} key={prompt.id}><span>{prompt.title}</span><ArrowRight aria-hidden="true" /></Link>)}</div></section>}<footer className="atelier-footer"><Link className="wordmark" href="/">PLS PROMPT</Link><span>Good ideas deserve a head start.</span></footer></div>;
}
