"use client";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Recipe } from "@/lib/recipe-types";
export function RecipeContentEditor({ recipe, onChange }: { recipe: Recipe; onChange: (recipe: Recipe) => void }) {
  function move(index: number, direction: number) { const parts = [...recipe.steps]; const next = index + direction; if (next < 0 || next >= parts.length) return; [parts[index], parts[next]] = [parts[next], parts[index]]; onChange({ ...recipe, steps: parts }); }
  return <div className="recipe-content-editor">{recipe.format === "skill" ? <>{recipe.files.map((file,index) => <div className="recipe-step-editor" key={index}><div className="recipe-step-toolbar"><span>File {index + 1}</span><Button type="button" variant="ghost" onClick={() => onChange({ ...recipe, files: recipe.files.filter((_,i) => i !== index) })} aria-label={`Remove file ${index + 1}`}><Trash2 /></Button></div><label>Filename<Input value={file.name} maxLength={120} onChange={e => onChange({ ...recipe, files: recipe.files.map((f,i) => i === index ? { ...f, name: e.target.value } : f) })} placeholder="SKILL.md" /></label><label>File contents<Textarea value={file.content} maxLength={30000} onChange={e => onChange({ ...recipe, files: recipe.files.map((f,i) => i === index ? { ...f, content: e.target.value } : f) })} /></label></div>)}<Button type="button" variant="outline" disabled={recipe.files.length >= 20} onClick={() => onChange({ ...recipe, files: [...recipe.files, { name: recipe.files.length ? `notes-${recipe.files.length}.md` : "SKILL.md", content: "" }] })}><Plus /> Add recipe file</Button></> : <>{recipe.steps.map((step,index) => <div className="recipe-step-editor" key={index}><div className="recipe-step-toolbar"><span>{recipe.format === "single" ? "Complete prompt" : `Step ${index + 1}`}</span>{recipe.format === "pack" && <div className="action-row"><Button type="button" variant="ghost" disabled={index === 0} onClick={() => move(index,-1)} aria-label={`Move step ${index + 1} up`}><ArrowUp /></Button><Button type="button" variant="ghost" disabled={index === recipe.steps.length - 1} onClick={() => move(index,1)} aria-label={`Move step ${index + 1} down`}><ArrowDown /></Button><Button type="button" variant="ghost" onClick={() => onChange({ ...recipe, steps: recipe.steps.filter((_,i) => i !== index) })} aria-label={`Remove step ${index + 1}`}><Trash2 /></Button></div>}</div>{recipe.format === "pack" && <label>Step title<Input value={step.title} maxLength={120} onChange={e => onChange({ ...recipe, steps: recipe.steps.map((s,i) => i === index ? { ...s, title: e.target.value } : s) })} /></label>}<label>Prompt instructions<Textarea value={step.text} maxLength={30000} onChange={e => onChange({ ...recipe, steps: recipe.steps.map((s,i) => i === index ? { ...s, text: e.target.value } : s) })} /></label></div>)}{recipe.format === "pack" && <Button type="button" variant="outline" disabled={recipe.steps.length >= 20} onClick={() => onChange({ ...recipe, steps: [...recipe.steps, { title: "", text: "" }] })}><Plus /> Add prompt step</Button>}</>}</div>;
}
